#!/usr/bin/env sh

if command -v cagro >/dev/null 2>&1; then
    $1/scripts/rust $1    
fi

cargo update
if ! cargo install --list | grep -q "^cargo-update v"; then
    cargo install cargo-update
fi

# CARGO ----------------------------------------------------
cargo install-update exa ripgrep

# PARU -----------------------------------------------------
paru -S --noconfirm brightnessctl
paru -S --noconfirm fzf


