#!/usr/bin/env bash

if command -v uv >/dev/null 2>&1; then
    exit 0
fi

if command -v cargo >/dev/null 2>&1; then
    cargo install --git https://github.com/astral-sh/uv uv
else
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

