#!/usr/bin/env bash

for file in "$1/bin/*"; do
    chmod +x $file
    echo "[INFO] script $file get +x permitions" 
done

rm -rf $XDG_DATA_HOME/bin
# TODO: move to .local/bin || .local/scripts
ln -s $1/bin $XDG_DATA_HOME/bin
